### ISSUE TITLE
serialization timeout even with vaadin.serialization.timeout set to 360000

### ISSUE THREAD

**Issue by jorgheymans** [vaadin/kubernetes-kit#103]
Hi,

For some of our larger pages, we are incurring serialization timeouts even when the timeout is set to 6 minutes. 

Regardless of how high we need to set this property to make it work, what is the devmode serialization debug doing that takes more than 6 minutes ? Is this to be expected ?

**Comment by tamasmak** [comment]
Hi @jorgheymans,
Have you already tried to set `logging.level.com.vaadin.kubernetes=trace`? The serialization debug tool will provide more logs about the process. What do you see then?
The serialization process steps are described in the [SessionSerializer](https://javadoc.io/doc/com.vaadin/kubernetes-kit-starter/latest/com/vaadin/kubernetes/starter/sessiontracker/SessionSerializer.html).

**Comment by jorgheymans** [comment]
Thank you, i will try your suggestion and report back. Apologies for the late reply.

Just curious, does the session serde mechanism support circular references? We have a large object tree in the session with lots of complex reference data and circular references between some of the classes sometimes happens because of the nature of the data.

**Comment by tamasmak** [comment]
Yes, the session serde mechanism uses the standard Java serialization that handles circular references. However, in some cases it may fail if there are self references on lambdas. You can read more and find suggestions about this case in the Kubernetes Kit [documentation](https://vaadin.com/docs/latest/tools/kubernetes/session-replication#serializedlambda-classcastexception).

**Comment by tamasmak** [comment]
Closing this issue as there are no more questions.
