### ISSUE TITLE
Add license checking to the kit

### ISSUE THREAD

**Issue by heruan** [vaadin/kubernetes-kit#33]
The kit needs license checking before being released. This could be done in a similar way as SSO Kit, i.e. with a custom condition on the auto-configuration class.

See [vaadin/sso-kit/.../LicenseCheckCondition.java](https://github.com/vaadin/sso-kit/blob/f0ccef4ce5a63d998be748318807602e233d285d/sso-kit-starter/src/main/java/com/vaadin/sso/starter/LicenseCheckCondition.java)

**Comment by Legioth** [comment]
As discussed in the daily, we could also consider making it so that having the Kit on the classpath while not explicitly configuring the Spring Boot autoconfiguration to be disabled would cause an exception to be thrown instead of only logging a warning.

**Comment by heruan** [comment]
I verified that auto-configuration classes not matching any condition are not even loaded i.e. static blocks are not evaluated.

That gives us the opportunity to use a static block for license checking and add a property condition to disable auto-configuration: this way the license check won't happen if the kit is explicitly disable and will throw if the kit is enable but no valid license is found.
