### ISSUE TITLE
Report Debug Tool outcomes in the browser

### ISSUE THREAD

**Issue by mcollovati** [vaadin/kubernetes-kit#46]
Currently, the Debug Tool prints results on server log.
It would be useful to also have some sort of notification on the browser, to have an immediate feedback.

**Comment by tarekoraby** [comment]
I think it would be sufficient to show a general alert in the browser saying something like "There was an error during (de)serialization. Go check the server log for more details." I think we shouldn't duplicate all the results in the browser.
