### ISSUE TITLE
Update Session Replication Debug Tool documentation to reflect latest changes

### ISSUE THREAD

**Issue by mcollovati** [vaadin/kubernetes-kit#67]
The latest version of Session Replication Debug Tool has some changes that should be documented.

The information to add are the following:

* the tool is composed by a combination of a Vaadin `RequestHandler` and an HTTP filter, but the documentation does not mention the filter.
* it should also be mentioned that the filter must be manually configured for non Spring Boot project
* the tool requires `sun.io.serialization.extendedDebugInfo` system property and `--add-opens java.base/java.io=ALL-UNNAMED` flag to be set before running the application
* example of output of the tool should be updated

**Comment by mcollovati** [comment]
I suppose this ticket can be closed, the documentation should be updated

**Comment by heruan** [comment]
Closed in https://github.com/vaadin/docs/pull/1931
