### ISSUE TITLE
Create a demo application to show the kit capabilities

### ISSUE THREAD

**Issue by heruan** [vaadin/kubernetes-kit#8]
All the kit capabilities should be demonstrated on a demo application that satisfies these requirements:

- it includes deployment descriptors to be deployed on a Kubernetes cluster
- it contains at least one view to show how the app is able to properly scale up/down
- it is monitored to show the performance impact of the kit when used with session serialization

**Comment by tarekoraby** [comment]
> it contains at least one view to show how the app is able to properly scale up/down

Other than scaling up/down, the demo should preferably also showcase the other two major capabilities of the Kit:

- High availability
- Rolling updates
